# EVE Copilot - Abyssal Running Profile
# Optimized for Abyssal pocket running scenarios

name: "Abyssal Running"
description: "Specialized profile for Abyssal pocket running with aggressive damage monitoring and rapid response alerts"

rules:
  # High-priority damage alerts for Abyssals
  pulse_shield_booster:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 3          # Trigger after 3 damage events
      sustained_damage: 2000 # Over 2 second period
    cooldown_ms: 6000        # 6 second cooldown (faster than general)
    window_ms: 2000          # 2 second window
    priority: 0              # Highest priority (safety)
    voice_prompt: "Pulse shield booster"
    description: "Immediate alert for sustained incoming damage in Abyssals"

  # Rapid drone recall for Abyssal scenarios
  recall_drones_abyssal:
    enabled: true
    event_types: ["DroneHit"]
    conditions:
      min_events: 1          # Trigger after just 1 drone hit (more aggressive)
      min_damage: 30         # Lower damage threshold
    cooldown_ms: 5000        # 5 second cooldown (faster than general)
    window_ms: 2000          # 2 second window
    priority: 1              # Medium priority
    voice_prompt: "Recall drones"
    description: "Quick drone recall for Abyssal pocket scenarios"

  # E-war alerts (same as general but faster response)
  you_scrammed_abyssal:
    enabled: true
    event_types: ["WarpScramble"]
    cooldown_ms: 8000        # 8 second cooldown (faster than general)
    priority: 0              # High priority (safety)
    voice_prompt: "You are scrambled"
    description: "Warp scramble alert for Abyssal scenarios"

  you_webbed_abyssal:
    enabled: true
    event_types: ["WebEffect"]
    cooldown_ms: 6000        # 6 second cooldown (faster than general)
    priority: 1              # Medium priority
    voice_prompt: "You are webbed"
    description: "Web alert for Abyssal scenarios"

  # Capacitor management (critical for Abyssals)
  cap_neutralized_abyssal:
    enabled: true
    event_types: ["EnergyNeutralization"]
    cooldown_ms: 5000        # 5 second cooldown (faster than general)
    priority: 0              # High priority (safety)
    voice_prompt: "Capacitor neutralized"
    description: "Critical alert for capacitor neutralization in Abyssals"

  cap_low_abyssal:
    enabled: true
    event_types: ["CapacitorStatus"]
    conditions:
      cap_threshold: 25      # Alert when cap below 25% (higher than general)
    cooldown_ms: 8000        # 8 second cooldown (faster than general)
    priority: 0              # High priority (safety)
    voice_prompt: "Capacitor low"
    description: "Early capacitor warning for Abyssal scenarios"

  # Shield management
  shield_low_abyssal:
    enabled: true
    event_types: ["ShieldStatus"]
    conditions:
      shield_threshold: 50   # Alert when shield below 50%
    cooldown_ms: 10000       # 10 second cooldown (faster than general)
    priority: 0              # High priority (safety)
    voice_prompt: "Shield low"
    description: "Early shield warning for Abyssal scenarios"

  # Equipment management
  reload_required_abyssal:
    enabled: true
    event_types: ["ReloadRequired"]
    cooldown_ms: 3000        # 3 second cooldown (faster than general)
    priority: 1              # Medium priority
    voice_prompt: "Reload now"
    description: "Quick reload alert for Abyssal scenarios"

  # Special Abyssal-specific alerts
  entering_abyss_greeting:
    enabled: false            # Disabled - too broad, triggers on any spatial phenomena
    event_types: ["SpatialPhenomena"]
    cooldown_ms: 10000        # prevent repeats on multiple similar lines
    priority: 2               # informational
    voice_prompt: "entering abyss, good hunting!"
    description: "Greet when local spatial phenomena (Abyssal effect) is detected"

  # NEW: Specific abyss entry detection
  abyss_entry_greeting:
    enabled: true
    event_types: ["AbyssEntry"]
    cooldown_ms: 30000        # 30 second cooldown (only once per entry)
    priority: 2               # informational
    voice_prompt: "entering abyss, good hunting!"
    description: "Greet when actually entering an Abyssal Deadspace pocket"

  abyssal_wave_complete:
    enabled: false
    event_types: ["IncomingDamage"]
    conditions:
      sustained_damage: 0     # No incoming damage for sustained period
      min_events: 0           # No damage events in window
    cooldown_ms: 30000        # 30 second cooldown (much longer)
    window_ms: 15000          # 15 second window to detect sustained no damage
    priority: 1              # Medium priority (tactical info)
    voice_prompt: "Wave complete"
    description: "Alert when no incoming damage for sustained period (wave complete) - DISABLED due to false positives"

  # NEW: Cargo collection phase
  cargo_collection_abyssal:
    enabled: true
    event_types: ["CargoApproach"]
    cooldown_ms: 8000        # 8 second cooldown
    priority: 2              # Low priority (informational)
    voice_prompt: "Collecting loot"
    description: "Alert when ship automatically approaches cargo for collection"

  # Overheat monitoring for Abyssal scenarios
  module_overheat_abyssal:
    enabled: true
    event_types: ["ModuleActivated"]
    conditions:
      module_types: ["Shield Booster", "Armor Repairer", "Afterburner"]
    cooldown_ms: 4000        # 4 second cooldown (faster than general)
    priority: 1              # Medium priority
    voice_prompt: "Module active"
    description: "Monitor key defensive modules in Abyssal scenarios"

  # Damage spike detection (more sensitive for Abyssals)
  damage_spike_abyssal:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 3          # Trigger after 3 damage events (less spammy)
      sustained_damage: 1500 # Higher threshold for actual spikes
    cooldown_ms: 8000        # 8 second cooldown (less frequent)
    window_ms: 2000          # 2 second window (more reasonable)
    priority: 0              # High priority (safety)
    voice_prompt: "Damage spike"
    description: "Sensitive damage spike detection for Abyssal scenarios"

  # Room cleared detection (intelligent combat completion detection)
  room_cleared_abyssal:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      sustained_damage: 0     # No incoming damage for sustained period
      min_events: 0           # No damage events in window
      time_since_last_damage: 8  # 8 seconds since last damage
    cooldown_ms: 20000        # 20 second cooldown (prevent spam)
    window_ms: 10000          # 10 second window to detect sustained no damage
    priority: 1              # Medium priority (tactical info)
    voice_prompt: "Room cleared"
    description: "Alert when no incoming damage for 8+ seconds (room cleared)"

  # Drone recall reminder when room is cleared
  drone_recall_reminder_abyssal:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      sustained_damage: 0     # No incoming damage for sustained period
      min_events: 0           # No damage events in window
    cooldown_ms: 30000        # 30 second cooldown (after room cleared)
    window_ms: 15000          # 15 second window to detect sustained no damage
    priority: 1              # Medium priority (tactical)
    voice_prompt: "Recall drones - room cleared"
    description: "Reminder to recall drones when room is cleared (15+ seconds no damage)"

  # Reload reminder when room is cleared
  reload_reminder_abyssal:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      sustained_damage: 0     # No incoming damage for sustained period
      min_events: 0           # No damage events in window
    cooldown_ms: 35000        # 35 second cooldown (after room cleared)
    window_ms: 18000          # 18 second window to detect sustained no damage
    priority: 1              # Medium priority (tactical)
    voice_prompt: "Reload weapons - room cleared"
    description: "Reminder to reload weapons when room is cleared (18+ seconds no damage)"

  # Time warning for 10-minute mark (critical timing)
  time_warning_abyssal:
    enabled: false
    event_types: ["SpatialPhenomena"]
    conditions:
      effect: "spatial_phenomena"
    cooldown_ms: 30000       # 30 second cooldown (only once per run)
    priority: 1              # Medium priority (time management)
    voice_prompt: "10 minutes elapsed - check your timer"
    description: "Warning at 10-minute mark in abyssal run"

  # 10-minute timer alert (based on time since abyss entry)
  timer_10min_abyssal:
    enabled: false
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 1          # Trigger on any damage event
      time_since_abyss: 600  # 10 minutes = 600 seconds
    cooldown_ms: 60000       # 1 minute cooldown (only once)
    priority: 1              # Medium priority (time management)
    voice_prompt: "10 minutes elapsed - check your timer"
    description: "Alert when 10 minutes have passed since entering abyss"

  # Recent abyss entry detection (for timing)
  recent_abyss_entry:
    enabled: false            # Disabled - too broad, triggers on any spatial phenomena
    event_types: ["SpatialPhenomena"]
    conditions:
      effect: "spatial_phenomena"
    cooldown_ms: 1000        # 1 second cooldown
    priority: 3              # Low priority (just for tracking)
    voice_prompt: "entering abyss, good hunting!"
    description: "Detect recent abyss entry for timing purposes"

  # Simple 10-minute timer (triggers on any recent damage after 10 minutes)
  simple_10min_timer:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 1          # Any damage event
      time_since_abyss: 600  # 10 minutes = 600 seconds
    cooldown_ms: 300000      # 5 minute cooldown (only once per run)
    priority: 1              # Medium priority (time management)
    voice_prompt: "10 minutes elapsed - check your timer"
    description: "Simple 10-minute timer based on recent abyss entry"

  # Energy neutralization alert
  energy_neutralization_abyssal:
    enabled: true
    event_types: ["EnergyNeutralization"]
    conditions:
      min_events: 1          # Any neutralization event
    cooldown_ms: 5000        # 5 second cooldown
    priority: 2              # Medium priority (energy management)
    voice_prompt: "Energy neutralized by {target_name}"
    description: "Alert when energy is being neutralized"

  # Combat detection (only trigger target recommendations during real combat)
  combat_detection_abyssal:
    enabled: false           # Disabled - no audio alert needed
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 1          # Any damage event
      sustained_damage: 20   # Lower threshold for all enemies
    cooldown_ms: 5000        # 5 second cooldown
    window_ms: 2000          # 2 second analysis window
    priority: 3              # Low priority (just for detection)
    voice_prompt: "Combat detected"
    description: "Detect when combat is happening"

  # Target recommendation system (prioritize most dangerous enemies)
  target_recommendation_abyssal:
    enabled: true
    event_types: ["IncomingDamage"]
    conditions:
      min_events: 1          # Trigger after 1 damage event (immediate response)
      sustained_damage: 20   # Match combat detection threshold
    cooldown_ms: 5000        # 5 second cooldown (very responsive)
    window_ms: 1000          # 1 second analysis window (immediate)
    priority: 1              # Medium priority (tactical)
    voice_prompt: "Recommended target: {target_name}"
    description: "Recommend the most dangerous enemy to target based on damage output and threat level"

  # Missile reload completion reminder
  missile_reload_reminder:
    enabled: true
    event_types: ["MissileReloadComplete"]
    cooldown_ms: 5000        # 5 second cooldown
    priority: 1              # Medium priority (tactical reminder)
    voice_prompt: "Missiles reloaded - re-enable launchers"
    description: "Reminder to re-enable missile launchers after they finish reloading"

  # Karybdis Tyrannos boss detection and tactical guidance
  karybdis_tyrannos_detected:
    enabled: true
    event_types: ["KarybdisTyrannosDetected"]
    cooldown_ms: 30000       # 30 second cooldown (only once per encounter)
    priority: 0              # Highest priority (critical boss)
    voice_prompt: "Karybdis Tyrannos detected! Approach at angle, then orbit close!"
    description: "Critical alert when Karybdis Tyrannos boss is detected - provides tactical guidance"

  karybdis_tyrannos_tactical_reminder:
    enabled: true
    event_types: ["KarybdisTyrannosOutgoing"]
    conditions:
      min_events: 3          # Trigger after dealing some damage
    cooldown_ms: 15000       # 15 second cooldown
    window_ms: 5000          # 5 second window
    priority: 0              # Highest priority (tactical guidance)
    voice_prompt: "Maintain close orbit! Stay under 5km!"
    description: "Tactical reminder to maintain close orbit around Karybdis Tyrannos"

  karybdis_tyrannos_damage_warning:
    enabled: true
    event_types: ["KarybdisTyrannosDetected"]
    conditions:
      min_events: 1          # Any damage from Karybdis
      sustained_damage: 1000 # High damage threshold
    cooldown_ms: 10000       # 10 second cooldown
    window_ms: 3000          # 3 second window
    priority: 0              # Highest priority (safety)
    voice_prompt: "Critical damage from Karybdis! Get closer immediately!"
    description: "Warning when taking high damage from Karybdis Tyrannos - indicates need to get closer"
